### ISSUE TITLE
How To Read This Book, indeed

### ISSUE THREAD

**Issue by bf4** [thoughtbot/ruby-science#172]
At first I really liked all the inter-linking, but then I became confused as to how I should read the book.

I think it's more of a reference, or maybe a choose-your-own adventure that doesn't really end. Calling it a book implies it can be read, but as described in the text, an expected way I might read may be:
1. Introduction
2. Case Statement, click Divergent Change
3. Read Divergent change till Solutions
4. Click Extract Class, read, then click on Large Class (or Divergent Change?)
5. Skip Divergent Change link, we've done that, read to solutions, click 'Move Method'
6. Click 'Feature Envy', that looks interesting
7. Oh yeah, 'Tell, Don't Ask', click, what was I doing again?
8. Great chapter, and hey, there's Case Statement again! Do I want to go back to that? Sure
9. Ok, Solutions, 'Replace Type Code with Subclasses', 
10. STI? Click
11. 'Composition over inheritance'!  I knew a guy who preferred inheritance over composition. He was a super guy (@tenderlove)
12. 'Extract Decorators', et cetera

I've tried to demonstrate how confusing the process of reading the book can be, with all the context switches.  Am I doing this wrong?  Maybe there should be backlinks in the margins like the letters on the spine of a dictionary?

There seems to be some internal logic linking all the sections together that isn't quite surfaced.

Do you think you'll have a summary table/page at any point that references all the sections?

**Comment by cpytel** [comment]
This has been a long time coming, but now the primary interface for Ruby Science is on the web at https://thoughtbot.com/ruby-science/introduction.html, I think this addresses the issue to the best of our ability as it is easier to follow internal links, view the table of contents all the time on the left hand side, and the browser back button can be used to follow a link and then get back to where you were before following it.

Thanks!
