### ISSUE TITLE
Access removed because I did not have two-factor auth

### ISSUE THREAD

**Issue by drogar** [thoughtbot/ruby-science#197]
Hi there
I previously had access to thoughtbot's ruby-science and testing-rails repositories. This was removed as I had not set up two-factor authorization.

I have changed my account to have two-factor authorization.

Could you restore my access to this repository and to the testing-rails  repository?

(The email from Github says to contact an owner in the org to get access restored. I did not have any email contacts, so I thought this was likely the best way to request access restoration).

**Comment by manolo07** [comment]
Can you make the for me, please?

Enviado desde mi iPhone

**Comment by drogar** [comment]
Sorry, I did not get that. You said "Can you make the for me, please?" 

What do you want me to make?

**Comment by cpytel** [comment]
Sorry for the trouble. We’ve actually made the repo for the books public, so there is no need to be a member of the org anymore.

You should now still be able to access the repository, as evidence by the fact that you’ve created this issue ;) Sorry for the confusion.

Thanks!
-Chad

**Comment by drogar** [comment]
Of course. Thanks!
